version: '2'
services:
  online_restoran-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/online_restoran/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
